### ISSUE TITLE
End-of-summer TODO list

### ISSUE THREAD

**Issue by gabrc52** [sipb/uplink#74]
By FPOP:

- [ ] Dormspam to get user feedback and more understanding of the messaging context before launching
- [ ] Ideal: User directory with People API (#53)
  - [ ] Override user directory endpoint
  - [ ] Override profile endpoint to not return 404 if the kerb does exist
  - [ ] **Very important**: Send emails to people who have not signed up but receive messages.
     - [ ] Create a Synapse module with a `on_new_event` callback
     - [ ] Handle DMs
     - [ ] Handle rooms
- [ ] Dormspam so people can know matrix.mit.edu exists

By registration:

- [ ] **Must have**: class group chats (#42)
   - [ ] Backend to create and join group chats, possibly the Interstellar backend itself or a custom endpoint in Synapse itself
   - [ ] Interstellar "Join group chat" or "Create group chat" button with a member count
   - [ ] Interstellar: warn anonymous users that they are joining a group chat where they can't be anonymous
   - [ ] Optional: Custom web app with minimal functionality but a class/group chat search
   - [ ] Judiciously use the Matrix directory itself

After the semester starts:

- [ ] Publicity: posters, lobby 10 tabling, possibly infinite display
- [ ] Develop the ability for everyone to create plumbed Messenger rooms in a user-friendly manner
- [ ] Second round of posters after this feature is added
- [ ] Documentation! We need our own docs on how to use Matrix, that are written with MIT's context in mind (for instance, instead of just saying "spaces exist" you can say "spaces exist which you can create for your club or organization and they are similar to Slack workspaces but with these differences")

Scalability:

- [ ] Set up workers (#73). Put that RAM to use and anticipate a large wave of users.
- [ ] Tune postgres options for performance (#43)

Once the stud reopens:

- [ ] Possibly set up RAIDs for data redundancy
- [ ] Move the mxc:// data store to HDDs if SSD performance is not necessary, or move sufficiently old media
- [ ] Set up postgres backups, e.g. https://gist.github.com/tcpipuk/f68fb199ea8b1c1bdf48833fde86b418
